### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewc910** [williampj/bridgeapi.js#36]
A list of things that need to get done before we are "done" with the backend. Feel free to edit this to add/check off TODO's.

### Frontend Pages
- [ ] Home - Status: In Progress
- [ ] About - Status: Not Started
- [ ] FAQS - Status Not Started
- [ ] Contact - Status Not Started

- [ ] Contact forms result in emails - Status: Not Started
- If users need to contact us for whatever reason, we need a contact form and a place for those to go.

### User Area

- [ ] Bridge Dropdown in Navbar - Status: Not Started
- TBD: I think it should be removed. It only results in extra api requests. Navigating to the dashboard and then to a bridge is 2 clicks from any page which isn't bad. 

- [ ] Sidebar API Request - Status: In Progress #30 

- [ ] Placeholder Environment Variables - Status: In Progress #35 

### Testing

- [ ] System Tests - Status: Not Started
- I believe we should integrate [Cypress](cypress.io) and write up some system tests for major functions such as creating/editing a bridge

### Deploy

- [ ] Deploy to AWS Lambda - Status: Not Started

### Bite Size

- [ ] Extract Snackbar messages into component
- Snackbar & Alert is being imported and hardcoded in a lot of places. I think it should be extracted into a separate component and pass in the message, severity, duration, state & handleClose function. Would help DRY things up.

- [ ] Eslint Fixes
- There is about 31 problems

- [ ] Rename requests to events 
- Includes requests page and requests components folder

- [ ] Sidebar title should link back to bridge
- [ ] Sidebar title is null on new pages resulting in no text, should say Untitled
- [ ] Remove `pages/api` folder
- This is for backend development but we use rails

- [ ] `formatDate` needs to be reworked for ruby timestamps
